apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: confluent-cli
  namespace: confluent
spec: 
  selector: 
    matchLabels: 
      app: confluent-cli
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: confluent-cli
    spec: 
      containers: 
      - name: confluent-cli
        image: confluentinc/confluent-cli:latest 
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]