apiVersion: v1
kind: Pod
metadata:
  name: mqttx-cli
  namespace: emqx-broker
spec:
  containers:
    - image: emqx/mqttx-cli
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always